apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinkPanther-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: demo
        image: pinkpantherbackend:latest
        ports:
        - containerPort: 3000
